namespace ExpressionEvaluator.LexicalAnalysis
{
	public enum TokenKind
	{
		Invalid,
		EndOfFile,
		Newline,
		Whitespace,
		Number,
		Plus,
		Minus,
		Star,
		Slash,
		OpenParen,
		CloseParen,
        Equal,
        NotEquals,
        Is,
        IsNot,
        Less,
        CloseAngleBracket,
        Negate,
        Assign,
        OpenAngleBracket,
        GreaterOrEqual,
        Caret,
        Identifier,
        Or,
        And,
        Percent,
        NotKeyword
    }
}